{
 "title": "Universal k6 Load&Performance Testing Dashboard (client-side metrics)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "worker_instance",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\""
   },
   {
    "name": "subscenario",
    "query": "SHOW TAG VALUES WITH KEY = \"subscenario\""
   },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "General Metrics (aggregated)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "k6_http_req_duration average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "med" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "p(95)" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "p(99)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "http_req_failed sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "Failed requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPS by http_reqs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* 1000 / $__interval_ms" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Rate $subscenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "Success % $tag_subscenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subscenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SuccessRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "subscenario", "operator": "=~", "value": "/^$subscenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Specific Metrics (by subscenario)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Duration Trend $subscenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "repeat": "subscenario",
   "targets": [
    {
     "alias": "$col $tag_subscenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subscenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DurationTrend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "med" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "p(95)" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "p(99)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "subscenario", "operator": "=~", "value": "/^$subscenario$/" }
     ]
    }
   ]
  },
  {
   "title": "RPS by Requests Counter $subscenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "subscenario",
   "targets": [
    {
     "alias": "RPS $tag_subscenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subscenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RequestsCounter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "subscenario", "operator": "=~", "value": "/^$subscenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Success Rate $subscenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "repeat": "subscenario",
   "targets": [
    {
     "alias": "Success % $tag_subscenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subscenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SuccessRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "subscenario", "operator": "=~", "value": "/^$subscenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate $subscenario",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "repeat": "subscenario",
   "targets": [
    {
     "alias": "Error % $tag_subscenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subscenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ErrorRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "subscenario", "operator": "=~", "value": "/^$subscenario$/" }
     ]
    }
   ]
  }
 ]
}